# Generated by Django 5.2.7 on 2025-11-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_forcemember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ro',
            name='name',
        ),
        migrations.AddField(
            model_name='ro',
            name='destination',
            field=models.CharField(default='RAB-1', max_length=100),
        ),
        migrations.AddField(
            model_name='ro',
            name='sing',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
