# Generated by Django 5.2.7 on 2025-11-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_ro_name_ro_destination_ro_sing'),
    ]

    operations = [
        migrations.AddField(
            model_name='acctbr',
            name='lpc',
            field=models.CharField(choices=[('other', ' '), ('lpcin', 'in'), ('lpcout', 'out')], default='lpcin', max_length=10),
        ),
    ]
